apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskboard
  labels:
    app.kubernetes.io/name: taskboard
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
spec:
  rules:
    - host: taskboard.home.arpa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskboard
                port:
                  name: http
