apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moomora-console
  labels:
    app.kubernetes.io/name: moomora-console
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
spec:
  rules:
    - host: moomora-console.home.arpa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moomora-console
                port:
                  name: http
